version: "3.8"
services:
  node-app:
    build:
      context: .
      target: development
    volumes:
      - .:/app:ro
    environment:
      - NODE_ENV=development





# version: "3.8"
# services:
#   node-app:
#     build:
#       context: .
#       args:
#         NODE_ENV: development
#     volumes:
#       - .:/app:ro
#     environment:
#       - NODE_ENV=development