version: "3.8"
services:
  node-app:
    build: 
      context: .
      target: production
    environment:
      - NODE_ENV=production







# version: "3.8"
# services:
#   node-app:
#     build: 
#       context: .
#       args:
#         NODE_ENV: production
#     environment:
#       - NODE_ENV=production